version: '3'
services:
  beat:
    image: docker.elastic.co/apm/apm-server:7.5.1
    ports:
      - "8200:8200"
      - "8201:8200"
    environment:
      - apm-server.host=0.0.0.0
    #volumes:
    #  - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    volumes:
      - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - apm
    depends_on:
      - elasticsearch
      - kibana
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    # network_mode: "service:elasticsearch"
    volumes:
        - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTIC_PASSWORD=WUHl8OGHl123
    networks:
      - apm
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    # volumes:
    #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - apm
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=WUHl8OGHl123
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:7.5.1
    ports:
      - "5044:5044"
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./logstash/logstash.conf:/config-dir/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - apm 
networks:
  apm:
    driver: bridge
